
version: '3.3'
services:
  perime-search-ms:
    image: golang:latest
    container_name: perime-search-ms
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: bash -c "
      go get -u github.com/go-sql-driver/mysql
      && go get -u github.com/gorilla/mux
      && go get
      && go run main.go
      "
    ports:
      - "1859:1859"
    depends_on:
      - perime-search-db
  perime-search-db:
    image: mariadb:latest
    container_name: perime-search-db
    restart: always
    environment:
      MYSQL_DATABASE: 'perime-search-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '60001:60001'
    expose:
      # Opens port 60001 on the container
      - '60001'
      # Where our data will be persisted
    volumes:
      - perime-search-db:/var/lib/mariadb
# Names our volume
volumes:
  perime-search-db:
